### ISSUE TITLE
One-to-One Messaging - Message Module

### ISSUE THREAD

**Issue by MrAlphalfa97** [chaneligans/Study-Chums#2]
- a 'message-sending' function that will write new Message documents to 'chat room'
- a 'message-receiving' function will read Message documents from the 'chat room' in real-time

**Comment by samanthawiley** [comment]
Wrote database functions for Firebase:
1. Create new Chat room
2. Add User to Chatroom
3. Load Chat History in Real-time
Helped refactor load and display chatroom functions
